apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.sabicallnative'
version = '1.0.0'

android {
  namespace 'expo.modules.sabicallnative'
}

dependencies {
  implementation 'androidx.core:core-ktx:1.13.1'
  implementation 'com.google.firebase:firebase-messaging:24.1.0'
}
